### ISSUE TITLE
Missing net ID - Extra Row added in PCB Layout

### ISSUE THREAD

**Issue by Kuurouukuu** [jeroen94704/klepcbgen#7] opened 2021-01-30 06:11 UTC
Attachment: JSON layout file, error image

[example_layout.txt](https://github.com/jeroen94704/klepcbgen/files/5897469/example_layout.txt)
![error_1](https://user-images.githubusercontent.com/55834878/106348870-2e1f0e80-62fc-11eb-80c7-03aa75a42679.png)

With that error and layout file, I did a bit of digging and found out that there is Row_6 that tied to net 0, which I'm not sure what it is. That row have only one key (I don't know what key it is) and 3 diodes. After remove those module, the PCB load successfully, but I'm not sure whether it is correct.

**Comment by Kuurouukuu** [comment] 2021-01-30 06:51
After digging around, I found out that Row_6 is tied to net 0 contains Down, Left and Right arrow. However the net is not declared in PCB file and is not connected to the chip. I have found out a work around by manually edit the kicad_pcd file to declare the net and connect it to unused pin of the chip in the PCB. Now it looks correct but will need further verification.

**Comment by jeroen94704** [comment] 2021-01-30 09:01
Thanks for this. This error is caused by the template only supporting up to 16 columns and up to 6 rows. Row 6 is the 7th row (it starts counting at 0), and therefore there is no pin on the microcontroller it can be attached to. I'll look into this.

**Comment by jeroen94704** [comment] 2021-01-30 10:06
Should be fixed with the latest commit. Turns out the schematic template included more rows/columns than the layout template (which had a few unconnected microcontroller pins). Please try again and let me know if you encounter any other issues.

**Closed by jeroen94704** 2021-01-30 10:06 UTC
