### ISSUE TITLE
*** footprint not found ***

### ISSUE THREAD

**Issue by MentalBlood** [jeroen94704/klepcbgen#5] opened 2020-11-11 21:40 UTC
Running example, can not load footprints from library:
![image](https://user-images.githubusercontent.com/31961163/98867290-63475d80-247f-11eb-9a8c-c7f6b157ee56.png)
[report.txt](https://github.com/jeroen94704/klepcbgen/files/5526874/report.txt)

**Comment by jeroen94704** [comment] 2021-01-28 18:32
Can you please let me know which version of KiCad you used? Also, the KLE json file that caused this would be helpful. Thanks!

**Comment by treypop** [comment] 2021-02-18 17:39
I had a similar problem your missing libraries

**Comment by jeroen94704** [comment] 2021-02-18 20:45
What version of KiCad are you using? Can you provide an example KLE json file that demonstrates the problem? Thanks!

**Comment by caffeinism** [comment] 2021-12-06 01:40
I use 5.1.12 and I have same problem

**Comment by caffeinism** [comment] 2021-12-06 02:17
I installed kicad on ubuntu and tried to run it, but it runs well in the same version.

**Comment by jeroen94704** [comment] 2021-12-07 10:43
Can you provide an example KLE file that demonstrates the problem? Thanks!

**Comment by caffeinism** [comment] 2021-12-07 11:43
I just use builtin example kle json file in the repository. I execute same procedure in ubuntu20.04 and windows10 in same kiCAD version.

**Comment by jeroen94704** [comment] 2022-10-28 07:10
Make sure you install the full version of kicad, as the "lite" version does not include the component symbol and footprint libraries

**Comment by jeroen94704** [comment] 2022-11-09 08:53
I suspect this is due to people installing the lite version of kicad. Closing as "can't reproduce". If others run into the same issue with the full kicad, feel free to open a new issue

**Closed by jeroen94704** 2022-11-09 08:53 UTC
