### ISSUE TITLE
Error loading board file: Invalid net ID

### ISSUE THREAD

**Issue by vicktorhu** [jeroen94704/klepcbgen#3] opened 2020-07-12 17:01 UTC
![image](https://user-images.githubusercontent.com/9425865/87252266-c6a68c00-c49b-11ea-9e29-fcc6892575cd.png)

JSON and kicad generated files are attached below.

[V79.zip](https://github.com/jeroen94704/klepcbgen/files/4908900/V79.zip)

Thank you!

**Comment by jeroen94704** [comment] 2020-10-28 08:55
duplicate of #4 , which is still open. I'll get around to this eventually :)

**Comment by jeroen94704** [comment] 2020-10-28 08:56
duplicate of #4

**Closed** 2020-10-28 08:57 UTC

**Comment by jeroen94704** [comment] 2021-01-28 18:31
Thanks for attaching a json file that reproduced the issue. This should be fixed now.
